const strings = {
  APP_NAME: "MSA Mart",
  NAME_PLACEHOLDER:"Enter your name",
  EMAIL_PLACEHOLDER:"Enter your registered email",
  EMAIL_PLACEHOLDER2:"Enter your email",
  PASSWORD_PLACEHOLDER:"Enter your password",
  LOGIN: "Log In",
  REGISTER: "Register",
  SEND: "Send",
  FULL_NAME:'Full Name',
  EMAIL: 'Email',
  PASSWORD:'Password',
  LOGINMESSAGE : 'Login Successful',
  CONFIRM_PASSWORD:'Confirm Password',
  RESET_PASSWORD: "Reset Password",
  ADD_ADDRESS: "Add Address",
  FIRST_NAME: "First Name",
  LAST_NAME: "Last Name",
  ADDRESS1: "Address 1",
  ADDRESS2: "Address 2",
  ZIP: "Zip",
  COUNTRY: "Country",
  EMIRATE: "Emirate",
  ContactUs: 'Contact Us',
  CITY: "City",
  AREA: "Area",
  PHONE_NUMBER:'Phone Number',
  UPDATE_ADDRESS:'Update Address',
  DOB: 'Date of birth',
  GENDER:'Gender',
  MOPHONE:'Mobile/Phone',
  SAVE:'Save',
  MALE:'Male',
  FEMALE:'Female',
  MOPHONE_REQUIRED:'Mobile/Phone Required',
  DOB_REQUIRED: 'Date of birth Required',
  FULL_NAME_REQUIRED:'Full Name Required',
  FIRST_NAME_REQUIRED: "First Name Required",
  LAST_NAME_REQUIRED: "Last Name Required",
  ADDRESS1_REQUIRED: "Address 1 Required",
  ADDRESS2_REQUIRED: "Address 2 Required",
  ZIP_REQUIRED: "Zip Code Required",
  PHNUMBER_REQUIRED: "Phone Number Required",
  FNAME_PLACEHOLDER: "First Name",
  FIRSTNAME_PLACEHOLDER: "First Name",
  LNAME_PLACEHOLDER: "Last Name",
  MOBILE_PLACEHOLDER: "Mobile Number",
  MOBILE_REQUIRED: "Valid Mobile Number Required.",
  DOB_PLACEHOLDER: "Date of Birth",
  GENDER_PLACEHOLDER: "Gender",
  NATIONALITY_PLACEHOLDER: "Nationality",
  TEMP_PASSWORD_PLACEHOLDER: "Temporary Password",
  NEW_PASSWORD_PLACEHOLDER: "New Password",
  EMAIL_REQUIRED: "Email is required",
  NAME_REQUIRED: "Name is required",
  FIRSTNAME_REQUIRED: "First Name is required",
  PASSWORD_REQUIRED: "Password is required",
  TEMP_PASSWORD_REQUIRED: "Temporary Password is required",
  NEW_PASSWORD_REQUIRED: "New password is required",
  CONFIRMPASSWORD_PLACEHOLDER: "Confirm password.",
  CONFIRMPASSWORD_REQUIRED: "Please Confirm your password.",
  EMAIL_WRONG_FORMAT: "Wrong Email format.",
  CONFIRMPASSWORD_DO_NOT_MATCH: "Confirm password do not match.",
  PASSWORD_WRONG_FORMAT: "Invalid password format",
  REGISTRATION_PASSWORD_WRONG_FORMAT: "Password Should have - 8 Characters, Atleast 1 upper case, 1 Lower case  & 1 Special character",
  YOUR_NAME: 'Your name',
  YOUR_EMAIL:'Your email',
  SUBJECT:'Subject',
  ENQUIRY:'Enquiry',
  SUBJECT_REQUIRED:'Subject is required',
  ENQUIRY_REQUIRED:'Enquiry text is required',
  SUBMIT:'SUBMIT',
  DELIVERY_PAGE_TITLE:'Help Center',
  RESET:'RESET',
  FRIENDS_EMAIL:"Friend's email",
  YOUR_EMAIL_ADDRESS:"Your email address",
  PERSONAL_MESSAGE:"Personal message",
  COMMENT_REQUIRED:"Name is required",
  ENTER:"Enter ",
  ShipmentDetails:"Shipment Details",
  AskUs:"Ask Us",
  PrivacyPolicy:"Privacy Policy",
  TermsConditions:"Terms and Conditions",
  Returns:"Returns",
YOUR_QUESTION:'Your Question',
LawsRegulations:'Laws and Regulations',
CLEAR:'Clear',
FILTERS:'Filters',

};

export default strings;
