const React = require('react-native');
const {  Dimensions,  StyleSheet,  PixelRatio, Platform} = React;
const {  width,  height} = Dimensions.get('window');
import {  Colors} from '@theme';

export default StyleSheet.create({
  scrollView: {
    backgroundColor: Colors.WHITE,
  },
  lottie:{
    height:100,
    width:100,
  },
  pageContainer: {
    margin: 15,
    marginBottom:80,
    width: width - 30,
    //height: 1500,
    borderRadius: 5,
    padding:15,
    alignItems:'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Colors.SILVER,
    backgroundColor: Colors.WHITE,
  },
  inputContainer:{
    width: width-60,
    alignSelf:'center',
  },
  inputContainerHalf:{
    //marginTop:45,
    marginRight:15,
    width: width/2,//(width-(width/3))-70,
    alignSelf:'center',
  },
  inputStyle:{
    width:width-100,
    paddingLeft:20,
    //backgroundColor:Colors.MORE_ORANGE,
  },
  dropdownContainer:{
    width:'100%',
    height:50,
    width: width-60,
    alignSelf:'center',
    borderWidth:1,
    borderColor:Colors.BLACK,
    borderRadius:30,
    flexDirection: 'row',
    marginTop:10,
  },
  codeDropdown:{
    width:(width/3)-10,
    height:50,
    alignSelf:'center',
    borderWidth:1,
    borderColor:Colors.BLACK,
    borderRadius:30,
    flexDirection: 'row',
    justifyContent:'center',
    //marginTop:10,
  },
  codeDropdownIos:{
    width:(width/3)-10,
    height:50,
    alignSelf:'center',
    borderWidth:1,
    borderColor:Colors.BLACK,
    borderRadius:30,
    flexDirection: 'row',
    justifyContent:'center',
    paddingTop:15,
    //marginTop:10,
  },
  codeDropdownInner:{
    paddingLeft:10,
    width:(width/3)-20,
    height:50,
    ///alignSelf:'center',
    //borderWidth:1,
    //borderColor:Colors.BLACK,
    //borderRadius:30,
    //flexDirection: 'row',
    //marginTop:10,
  },
  phoneContainer:{
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'space-between',
  },
  phCodeCont:{
    flexDirection:'column',
    marginLeft:15,
  },
  pickerStyle:{
    width: width-60,
    alignSelf:'center',
  },
  ddLabelStyle:{
    marginLeft:8, 
    fontSize:14, 
    color:Colors.DARK_GRAY_TEXT, 
    alignItems:'center', 
    alignSelf:'center', 
		...Platform.select({
			ios: {
				fontWeight: '400',
				fontFamily: 'verdana',
			},
			android: {
				fontWeight: 'normal',
				fontFamily: 'verdana',
			},
		}),
  },
  titleStyle:{
    margin:20,
    marginLeft:15,
    marginBottom:-5,
    fontSize:14,
    color:Colors.GRAY_TEXT,
    alignItems:'flex-start',
    alignSelf:'flex-start',
		...Platform.select({
			ios: {
				fontWeight: '400',
				fontFamily: 'verdana',
			},
			android: {
				fontWeight: 'normal',
				fontFamily: 'verdana',
			},
		}),
  },
  dtPickerTitleText:{
    margin:5,
    marginTop:15,
    marginLeft:15,
    alignItems:'flex-start',
    alignSelf:'flex-start',
		...Platform.select({
			ios: {
				fontWeight: '400',
				fontFamily: 'verdana',
			},
			android: {
				fontWeight: 'normal',
				fontFamily: 'verdana',
			},
		}),
    fontSize:13,
    color:Colors.GRAY_TEXT,
  },
  dtPickerContainer:{
    //margin:15,
    //alignSelf:'flex-start',
    alignItems:'flex-start',
    //justifyContent:'flex-start',
    borderRadius:50,
    width:width-60,
    height:50,
    borderWidth:1,
    borderColor:Colors.BLACK,
  },
  dateTxt:{
    margin:5,
    marginTop:15,
    marginLeft:15,
    alignItems:'flex-start',
    alignSelf:'flex-start',
		...Platform.select({
			ios: {
				fontWeight: '400',
				fontFamily: 'verdana',
			},
			android: {
				fontWeight: 'normal',
				fontFamily: 'verdana',
			},
		}),
    fontSize:13,
    color:Colors.GRAY_TEXT,
  },
  genderContainer:{
    width:width-30,
    flexDirection:'row',
    //alignItems:'center',
    //alignSelf:'center',
    //justifyContent:'center',
  },
  genderBtn:{
    margin:15,
    marginTop:10,
    marginLeft:15,
    marginRight:0,
    marginBottom:0,
    flexDirection:'row',
    width: (width-75)/2,
    height:50,
    borderRadius:50,
    borderWidth:1,
    borderColor:Colors.BLACK,
    //alignItems:'flex-start',
    //alignSelf:'flex-start',
    //justifyContent:'space-around',
  },
  selectedRadio:{
    margin:5,
    marginLeft:10,
    alignItems:'center',
    alignSelf:'center',
    height:18,
    width:18,
    borderRadius:10,
    borderWidth:1,
    borderColor:Colors.PRIMARY,
    justifyContent:'center',
  },
  selectedInner:{
    //margin:5,
    //marginLeft:10,
    alignItems:'center',
    alignSelf:'center',
    height:12,
    width:12,
    borderRadius:10,
    backgroundColor:Colors.PRIMARY,
  },
  unSelectedRadio:{
    margin:5,
    marginLeft:10,
    alignItems:'center',
    alignSelf:'center',
    height:18,
    width:18,
    borderRadius:10,
    borderWidth:1,
    borderColor:Colors.GRAY_TEXT,
  },
  genderTitleText:{
    margin:5,
    alignItems:'flex-start',
    alignSelf:'center',
		...Platform.select({
			ios: {
				fontWeight: '400',
				fontFamily: 'verdana',
			},
			android: {
				fontWeight: 'normal',
				fontFamily: 'verdana',
			},
		}),
    fontSize:13,
    color:Colors.GRAY_TEXT,
  },
});