const React = require('react-native');
const {  Dimensions,  StyleSheet,  PixelRatio, Platform} = React;
const {  width,  height} = Dimensions.get('window');
import {  Colors} from '@theme';

export default StyleSheet.create({
  scrollView: {
    backgroundColor: Colors.WHITE,
    marginBottom:70,
  },
  pageContainer: {
    margin: 15,
    marginBottom:80,
    width: width - 30,
    //height: 1500,
    borderRadius: 5,
    padding:15,
    alignItems:'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Colors.SILVER,
    backgroundColor: Colors.WHITE,
    shadowColor: Colors.LIGHT_GRAY,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 3,
  },
  inputContainer:{
    width: width-60,
    alignSelf:'center',
  },
  inputContainerHalf:{
    //marginTop:45,
    marginRight:15,
    width: width/2,//(width-(width/3))-70,
    alignSelf:'center',
  },
  inputStyle:{
    width:width-100,
    paddingLeft:20,
    //backgroundColor:Colors.MORE_ORANGE,
  },
  dropdownContainer:{
    height:50,
    width: width-60,
    alignSelf:'center',
    borderWidth:1,
    borderColor:Colors.BLACK,
    borderRadius:30,
    flexDirection: 'row',
    justifyContent:'center',
    marginTop:10,
  },
  dropdownContainerInner:{
    width:'100%',
    height:50,
    marginLeft:0,
    width: width-90,
    alignSelf:'center',
    //borderWidth:1,
    //borderColor:Colors.BLACK,
    //borderRadius:30,
    flexDirection: 'row',
    //marginTop:10,
  },
  dropdownContainerIos:{
    height:50,
    width: width-60,
    alignSelf:'flex-start',
    alignItems:'flex-start',
    borderWidth:1,
    borderColor:Colors.BLACK,
    borderRadius:30,
    flexDirection: 'row',
    //justifyContent:'center',
    marginTop:10,
    //paddingTop:10,
  },
  codeDropdown:{
    width:(width/3)-10,
    height:50,
    alignSelf:'center',
    borderWidth:1,
    borderColor:Colors.BLACK,
    borderRadius:30,
    flexDirection: 'row',
    justifyContent:'center',
    //marginTop:10,
  },
  codeDropdownIos:{
    width:(width/3)-10,
    height:50,
    alignSelf:'center',
    borderWidth:1,
    borderColor:Colors.BLACK,
    borderRadius:30,
    flexDirection: 'row',
    justifyContent:'center',
    //paddingTop:15,
    marginTop:10,
    alignItems:'flex-start',
    //backgroundColor:Colors.MORE_ORANGE,
  },
  codeDropdownInner:{
    paddingLeft:10,
    width:(width/3)-20,
    height:50,
    ///alignSelf:'center',
    //borderWidth:1,
    //borderColor:Colors.BLACK,
    //borderRadius:30,
    //flexDirection: 'row',
    //marginTop:10,
  },
  phoneContainer:{
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'space-between',
  },
  phCodeCont:{
    flexDirection:'column',
    marginLeft:15,
  },
  pickerStyle:{
    width: width-60,
    alignSelf:'center',
  },
  ddLabelStyle:{
    marginLeft:8, 
    fontSize:14, 
    color:Colors.DARK_GRAY_TEXT, 
    alignItems:'center', 
    alignSelf:'center', 
		...Platform.select({
			ios: {
				fontWeight: '400',
				fontFamily: 'verdana',
			},
			android: {
				fontWeight: 'normal',
				fontFamily: 'verdana',
			},
		}),
  },
  titleStyle:{
    margin:20,
    marginLeft:15,
    marginBottom:-5,
    fontSize:14,
    color:Colors.GRAY_TEXT,
    alignItems:'flex-start',
    alignSelf:'flex-start',
		...Platform.select({
			ios: {
				fontWeight: '400',
				fontFamily: 'verdana',
			},
			android: {
				fontWeight: 'normal',
				fontFamily: 'verdana',
			},
		}),
  },
  lottie:{
    height:100,
    width:100,
  },
});